### ISSUE TITLE
The blockchain download

### ISSUE THREAD

**Issue by leandrogomesmachado** [MatthewLM/peercoinj#2]
Hello, I am with a little trouble with the J server and Android Wallet, did you get a problem to download the blockchain properly?
I am working hard here but I can't figure where is the problem, the Android Wallet download the chain only to 12 or 13 hours behind the main chain, located at block explorer. 
I found that are with URL exception with ?package=kobocoin_android_wallet here but I update and I am testing... I think that will not work good, but I don't know where I need to change.

Matthew, I know that you are very busy guy, but please can you give me help? I need finish this two wallets, I will send now to github and will send to you a pushback from the code. Back soon

**Comment by leandrogomesmachado** [comment]
Actual problem is this, only show this blocks, the wallet stuck and not download new blocks. what I need to do?

**Comment by leandrogomesmachado** [comment]
Found here on HtmlcoinJ the problem that are causing this issue in KobocoinJ and HtmlcoinJ.

After debugging I get this:

```
04-13 20:42:15.871  19782-21326/com.bushstar.htmlcoin_android_wallet I/WalletFiles﹕ [Wallet autosave thread] Background saving wallet, last seen block is 310761/0000000107ca803df96760e0bb11b759a1f56d3b6509a814a1b8a9fcaa38c699
04-13 20:42:15.891  19782-21326/com.bushstar.htmlcoin_android_wallet I/WalletFiles﹕ [Wallet autosave thread] Save completed in 19msec
04-13 20:42:16.891  19782-21326/com.bushstar.htmlcoin_android_wallet I/WalletFiles﹕ [Wallet autosave thread] Background saving wallet, last seen block is 310793/000000003229c9b24622c6d2e1f34193d2a8945a50d96b6d541727b7a66eabf5
04-13 20:42:16.911  19782-21326/com.bushstar.htmlcoin_android_wallet I/WalletFiles﹕ [Wallet autosave thread] Save completed in 13msec
04-13 20:42:17.531  19782-20968/com.bushstar.htmlcoin_android_wallet W/Peer﹕ [NioClientManager] [192.168.1.2]:6877: Block verification failed
    com.bushstar.htmlcoinj.core.VerificationException: Could not verify block 00000000c06639b2ad26da1c35c99c1bc63fe8bf5ab2294c9c104395cbe5361a
    v6 block:
    previous block: 000000003229c9b24622c6d2e1f34193d2a8945a50d96b6d541727b7a66eabf5
    merkle root: 176832b7ee2331a3ec3de00109aff390fe829e3a0b35bd5bc025cba5e4dbaa0c
    time: [1428928358] Mon Apr 13 09:32:38 GMT-03:00 2015
    difficulty target (nBits): 486592397
    nonce: 228847234
    with 4 transaction(s):
    8ecaa535b6be572dd8ccffb0a996d165914898b5bd7fac300c3e0bb825386994:
    == COINBASE TXN (scriptSig [0abe04] [68b72b55] [47ffff6200000000] [2f6e6f64655374726174756d2f])  (scriptPubKey [03d64dd2e125dbade321f6680e2953fd48750927ab60c30b66e8a88ae5a63be129] CHECKSIG)
    b55b838df7568011edf73920217f4a4b8eb57ac192c2b34ee52499476b3c844d:
    in   [3045022100cef31615e4a4446a063689a64a4160d8d5f4cfc15e10192cd2a5b7f115f2f05802202a73323494a10c3966227ca137cbc0eed2dbaf14d36e7fa723cf9a6843153f6501] [02c0f7ed7068f5ca2f6ea81b696ce92d3f6cb7e6ff2ba1d186cab8e2c3f09fef3d]
    outpoint:ec40e9effad03f92225c52cb0556f9b0b096dc80effa1c38f690e0d0c6284fa7:1
    in   [30440220418a62cdc5ccdc11d906bddf4282a0801bb74296fae8d84583fa26ef3421b1e802205f755f99bb29427001b646759c5d56209f134e35ce6ef66bf9230cfd9149ee1501] [03d884cd67abc5902f9421296f9dbbdbede0e7072f90b046923412ad554951f529]
    outpoint:d0e0e9592eff0e5183a568124ca88603cf16bc20f951b301fe001ab611637798:1
    in   [304402204a843adeab4e5c72f8f5951d2e80c17aebd194c3259f0216755ed8235aa28ab102202beeb2ee82dbc8ef2a028b1530ef89d43fb1725bbf05118bb03b718579bfc9e201] [03d884cd67abc5902f9421296f9dbbdbede0e7072f90b046923412ad554951f529]
    outpoint:bd32e86bc20ffc655c51eb1b75443fadd77a434281fc28312f55c23baf3e44bb:0
    out  DUP HASH160 [aae97c131a523c72096963c4130441865c03f267] EQUALVERIFY CHECKSIG 1.52406 HTML
    out  DUP HASH160 [e011699c3bcbc1a9027932c8519bedd61aa1f0dc] EQUALVERIFY CHECKSIG 12499999.90 HTML
    a0bd076301622fe14d1d222c4d3d647df9851d62d93db008f970b36d52cc7faa:
    in   [30440220663786714e9670e05cb6dfec4aba5e8fa0df46846b56630a11aacde2afe1797302207a596406070c2f199c0180dda01ec8b8ec2fadafae46e81c48c1fa1b03bdea6901] [0244fd0d2f8688309c0bd89ad0d7b29209a326c319c9bdfc3cbcebc22241bfb737]
    outpoint:115752834559f84febce9f7012d7c116ddfb5ee410f08ce51dcf175bd92de68d:0
    out  DUP HASH160 [222630ee0cb26c0512ce8dc6a377499c94fec01c] EQUALVERIFY CHECKSIG 1935154.285 HTML
    out  DUP HASH160 [910dd8e93eb0002a8e07ec716e80ff177881f2fb] EQUALVERIFY CHECKSIG 13076.00 HTML
    63eb940c47477d9db17c66bf9ec73f2dad874a4771cf39718d1741faa8b6d6de:
    in   [3044022008fc90fa010327b6af1441fb0d73da7a8cd1a241fa10982eea07fda0b087d7d40220367dd670171fa46c402b811dd2d27d8ed41bc0e79c8b0643263d4df5905f102a01] [0326efd1231f5b030537c4fd7071e5da1c648d09b21224b64e63b4be29e3bfa9c6]
    outpoint:0c75d552b134e375dfc309d64d0cbd62ee24a0f56863f3aa0e06c96140856bd1:0
    out  DUP HASH160 [82849cdeed5ed9081f488ff9fcc42c863fbcd86d] EQUALVERIFY CHECKSIG 1527202.2363 HTML
    out  DUP HASH160 [5b58391cb102972f22039f89d16f5a4560e52679] EQUALVERIFY CHECKSIG 1223.42 HTML
            at com.bushstar.htmlcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:268) ~[na:0.0]
            at com.bushstar.htmlcoinj.core.Peer.processBlock(Peer.java:799) ~[na:0.0]
            at com.bushstar.htmlcoinj.core.Peer.processMessage(Peer.java:320) ~[na:0.0]
            at com.bushstar.htmlcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:183) ~[na:0.0]
            at com.bushstar.htmlcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:216) ~[na:0.0]
            at com.bushstar.htmlcoinj.net.NioClientManager.handleKey(NioClientManager.java:74) ~[na:0.0]
            at com.bushstar.htmlcoinj.net.NioClientManager.run(NioClientManager.java:110) ~[na:0.0]
            at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60) ~[na:0.0]
            at com.google.common.util.concurrent.Callables$3.run(Callables.java:93) ~[na:0.0]
            at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
     Caused by: com.bushstar.h
04-13 20:42:17.541  19782-20968/com.bushstar.htmlcoin_android_wallet I/AbstractBlockChain﹕ [NioClientManager] 36 blocks per second
04-13 20:42:17.551  19782-20968/com.bushstar.htmlcoin_android_wallet W/AbstractBlockChain﹕ [NioClientManager] Block does not connect: 000000008424263cb66cffc0db34b35dd9c1aa9262d13c80df9d21e2dca146fe prev 00000000c06639b2ad26da1c35c99c1bc63fe8bf5ab2294c9c104395cbe5361a
04-13 20:42:17.571  19782-20968/com.bushstar.htmlcoin_android_wallet W/AbstractBlockChain﹕ [NioClientManager] Block does not connect: 00000000fcd6b1368bae93ed2646f6e43a3d1c29520fb0472931da25e4c6ee8e prev 000000008424263cb66cffc0db34b35dd9c1aa9262d13c80df9d21e2dca146fe
04-13 20:42:17.571  19782-20968/com.bushstar.htmlcoin_android_wallet I/Peer﹕ [NioClientManager] blockChainDownloadLocked(000000008424263cb66cffc0db34b35dd9c1aa9262d13c80df9d21e2dca146fe): ignoring dup
```

You can get here the full log:
http://pastebin.com/hZiUiXEy

I know that is a checksig problem, but I don't know how to solve it.

**Comment by HashEngineering** [comment]
This log doesn't contain enough information.  There is a VerificationException that is triggered.
com.bushstar.htmlcoinj.core.VerificationException: Could not verify block 00000000c06639b2ad26da1c35c99c1bc63fe8bf5ab2294c9c104395cbe5361a
        at com.bushstar.htmlcoinj.core.AbstractBlockChain.add(AbstractBlockChain.java:268) ~[na:0.0]
... 
     Caused by: com.bushstar.h

The exception is thrown when the block is added to the blockchain because of some error, which could be the proof of work check, difficulty bits don't match or other reasons.  The line that says "Caused by: com.bustar.h" needs to be expanded to see where the VerificationException is thrown.

**Comment by leandrogomesmachado** [comment]
The difficulty target does not match nbits I think, the link for pastebin gave the full log with full informations. 
I will upload today the updated code of htmlcoinj to see. Thank you

**Comment by leandrogomesmachado** [comment]
@HashEngineering @MatthewLM Here are the code updated:
Android Wallet: https://github.com/machado-rev/htmlcoin-android-wallet
J Server (HtmlcoinJ): https://github.com/machado-rev/htmlcoinj
